export const DEMO_DATA: Record<"ecommerce" | "saas" | "food", { label: string; complaints: string }> = {
  ecommerce: {
    label: "E-commerce",
    complaints: [
      "Checkout keeps failing at payment step. This is the 3rd time. Switching to Amazon.",
      "Got charged twice for the same order. Support hasn't replied in 3 days.",
      "Search is completely broken. Can't find products that I know exist.",
      "Order tracking hasn't updated in 5 days. No idea where my package is.",
      "Refund was promised in 3-5 days, it's been 2 weeks. Terrible.",
      "App crashes every time I try to apply a coupon code.",
      "Images don't load on product pages. Looks broken and untrustworthy.",
      "Can't update my delivery address after placing order. Basic feature missing.",
      "Payment failed but money got deducted. Very stressful experience.",
      "Filter options reset every time I go back. Extremely frustrating.",
      "Guest checkout is broken. Forced to create account just to buy.",
      "No email confirmation received after purchase. Don't know if order went through.",
      "App is unbearably slow on 4G. Competitor app works fine.",
      "Size chart is missing on most products. Leads to wrong orders.",
      "Wishlist items disappear after logout. Lost my entire saved list.",
      "Return process is 10 steps long. Way too complicated.",
      "Discount code applied but full price charged. Feel cheated.",
      "Product arrived damaged. Raising complaint was a nightmare.",
      "No COD option available in my city. Lost a sale right there.",
      "App keeps logging me out randomly. Have to login every session.",
    ].join("\n"),
  },
  saas: {
    label: "SaaS Tool",
    complaints: [
      "Dashboard takes 8-10 seconds to load. Unusable for daily work.",
      "CSV export is completely broken. Get an empty file every time.",
      "Billing page shows wrong plan. I upgraded but it still shows free.",
      "Onboarding flow is confusing. Spent 20 mins and still couldn't set up basic integration.",
      "No bulk delete option. Have to delete records one by one.",
      "API rate limits are not documented anywhere. Kept hitting errors.",
      "Search doesn't support filters. Can't find anything in large datasets.",
      "Email notifications stopped working 2 weeks ago. Missed critical alerts.",
      "Can't invite team members without them receiving 4 confusing emails.",
      "Dark mode is broken on the reports page. Text becomes invisible.",
      "Session expires too quickly. Get logged out mid-work constantly.",
      "No undo option after bulk actions. Accidentally deleted important data.",
      "Mobile app is missing 60% of features from desktop. Useless on phone.",
      "Integrations page crashes on Safari. Can't connect our tools.",
      "Audit logs are not exportable. Compliance team is blocked.",
      "Charts don't render on slow connections. Just shows blank.",
      "Password reset email goes to spam every single time.",
      "Can't customize notification preferences. Getting spammed.",
      "API docs are outdated. Half the endpoints in docs don't work.",
      "No keyboard shortcuts. Power users are stuck clicking everything.",
    ].join("\n"),
  },
  food: {
    label: "Food Delivery",
    complaints: [
      "Order was 45 mins late and arrived cold. Completely inedible.",
      "Wrong items delivered. Asked for vegetarian, got non-veg. Unacceptable.",
      "Refund rejected even though I sent photos. Support is useless.",
      "App crashed during checkout. Order didn't go through but got charged.",
      "Restaurant shows as open but order got cancelled after 30 mins.",
      "Driver location on map was completely wrong. Waited outside for nothing.",
      "No option to add delivery instructions. Food left at wrong building.",
      "Promo code not working even though it's not expired.",
      "Customer support chat takes 45 mins to respond. Problem already resolved itself.",
      "Can't reorder from past orders. Have to manually find everything again.",
      "App doesn't remember my address. Have to re-enter every time.",
      "Payment failed but cart got cleared. Had to start over completely.",
      "Estimated time was 20 mins, actual time was 75 mins. No updates.",
      "Rating system doesn't work. Can't leave reviews after delivery.",
      "Subscription benefits not applying at checkout. Paying full price.",
      "No way to split payment between wallet and card.",
      "Order tracking stuck at 'preparing' for 1 hour.",
      "Can't cancel order even 30 seconds after placing it.",
      "Photos on menu don't match actual food. Misleading.",
      "App sends duplicate notifications for every order update.",
    ].join("\n"),
  },
};
