import type { Issue, IssueStatus, PrdStub } from "./types";

const KEY = "buildmonday:integrations";

export interface IntegrationsConfig {
  github?: { owner: string; repo: string };
}

export function loadIntegrations(): IntegrationsConfig {
  if (typeof window === "undefined") return {};
  try {
    const raw = window.localStorage.getItem(KEY);
    return raw ? (JSON.parse(raw) as IntegrationsConfig) : {};
  } catch {
    return {};
  }
}

export function saveIntegrations(cfg: IntegrationsConfig) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(KEY, JSON.stringify(cfg));
  } catch {
    // ignore
  }
}

const ACTION_LABEL: Record<Issue["recommended_action"], string> = {
  fix_now: "Fix Now",
  investigate: "Investigate",
  monitor: "Monitor",
};

const STATUS_LABEL: Record<IssueStatus, string> = {
  backlog: "Backlog",
  in_progress: "In Progress",
  shipped: "Shipped",
};

const bullets = (arr: string[]) => arr.map((x) => `- ${x}`).join("\n");

export function buildIssueMarkdown(
  issue: Issue,
  prd: PrdStub | null,
  status: IssueStatus = "backlog"
): { title: string; body: string } {
  const title = `[BuildMonday] ${issue.title}`;

  const evidence = issue.evidence.slice(0, 3).map((e) => `> "${e}"`).join("\n");

  const prdBlock = prd
    ? `

## PRD Stub

**Problem Statement:** ${prd.problem_statement}

**Affected Users:**
${bullets(prd.affected_users)}

**Acceptance Criteria:**
${bullets(prd.acceptance_criteria)}

**Edge Cases:**
${bullets(prd.edge_cases)}

**Success Metrics:**
${bullets(prd.success_metrics)}

**Implementation Notes:** ${prd.implementation_notes}

**Estimated Complexity:** ${prd.estimated_complexity}`
    : "";

  const body = `**Priority:** ${ACTION_LABEL[issue.recommended_action]} | **Severity:** ${issue.severity} | **Churn Risk:** ${issue.churn_risk} | **Effort:** ${issue.effort} | **Status:** ${STATUS_LABEL[status]}
**Affected:** ${issue.affected_segment}
**Frequency:** ${issue.frequency} complaint${issue.frequency === 1 ? "" : "s"}

## Why this ranks here
${issue.ranking_reason ?? "_Not provided._"}

## Evidence
${evidence}${prdBlock}

---
_Generated by BuildMonday from customer complaints._`;

  return { title, body };
}

export function parseGithubRepo(
  rawOwner: string,
  rawRepo: string
): { owner: string; repo: string } | null {
  const combined = `${rawOwner} ${rawRepo}`;
  const urlMatch = combined.match(
    /github\.com[/:]([A-Za-z0-9._-]+)\/([A-Za-z0-9._-]+?)(?:\.git)?(?:[/?#\s]|$)/i
  );
  if (urlMatch) {
    return { owner: urlMatch[1], repo: urlMatch[2] };
  }
  for (const candidate of [rawOwner.trim(), rawRepo.trim()]) {
    const slashMatch = candidate.match(
      /^([A-Za-z0-9._-]+)\/([A-Za-z0-9._-]+?)(?:\.git)?\/?$/
    );
    if (slashMatch) {
      return { owner: slashMatch[1], repo: slashMatch[2] };
    }
  }
  const o = rawOwner.trim().replace(/\/$/, "");
  const r = rawRepo.trim().replace(/\/$/, "").replace(/\.git$/i, "");
  if (o && r && /^[A-Za-z0-9._-]+$/.test(o) && /^[A-Za-z0-9._-]+$/.test(r)) {
    return { owner: o, repo: r };
  }
  return null;
}

const GITHUB_BODY_LIMIT = 6000;

export function buildGitHubIssueUrl(
  owner: string,
  repo: string,
  title: string,
  body: string
): string {
  const safeOwner = encodeURIComponent(owner.trim());
  const safeRepo = encodeURIComponent(repo.trim());
  const truncated =
    body.length > GITHUB_BODY_LIMIT
      ? body.slice(0, GITHUB_BODY_LIMIT) +
        "\n\n_…truncated. Full PRD on the original BuildMonday session._"
      : body;
  const params = new URLSearchParams({ title, body: truncated });
  return `https://github.com/${safeOwner}/${safeRepo}/issues/new?${params.toString()}`;
}
